name: "interactiveart.io"
description: "course site for interactive art & creative coding"

#url: "http://interactiveart.io"
url: "http://0.0.0.0:4000"

collections:
  ofbook:
    output: true
    permalink: /:path/

post_defaults:
  layout: post

sass:
    sass_dir: _sass

highlighter: pygments

encoding: UTF-8